### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/path/to/project/.hg/branch

### ISSUE THREAD

**Issue by richarddewit** [victor-torres/atom-hg#1]
Thanks for creating this package! I really really needed a Mercurial package for Atom :)
## Steps to reproduce
1. Have tabs open
2. Try to close all tabs
3. On last tab close, error is thrown and tab is still opened
## Info

**Atom Version**: 1.6.0
**System**: Linux Mint
**Thrown From**: [atom-hg](https://github.com/victor-torres/atom-hg) package, v0.0.7
## Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/path/to/project/.hg/branch'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/path/to/project/.hg/branch'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Repository.getShortHead (/home/richard/.atom/packages/atom-hg/lib/hg-utils.coffee:97:15)
    at HgRepository.module.exports.HgRepository.getShortHead (/home/richard/.atom/packages/atom-hg/lib/hg-repository.coffee:169:42)
    at status-bar-git.GitView.updateBranchText (/opt/atom/resources/app.asar/node_modules/status-bar/lib/git-view.js:179:37)
    at status-bar-git.GitView.update (/opt/atom/resources/app.asar/node_modules/status-bar/lib/git-view.js:170:12)
    at status-bar-git.GitView.subscribeToActiveItem (/opt/atom/resources/app.asar/node_modules/status-bar/lib/git-view.js:81:19)
    at /opt/atom/resources/app.asar/node_modules/status-bar/lib/git-view.js:24:24
    at Function.module.exports.Emitter.simpleDispatch (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /opt/atom/resources/app.asar/src/pane-container.js:346:27
    at Function.module.exports.Emitter.simpleDispatch (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (/opt/atom/resources/app.asar/src/pane.js:255:22)
    at Pane.module.exports.Pane.removeItem (/opt/atom/resources/app.asar/src/pane.js:463:16)
    at Pane.module.exports.Pane.destroyItem (/opt/atom/resources/app.asar/src/pane.js:532:16)
    at atom-tabs.TabBarView.onMouseDown (/opt/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:601:19)
```

**Comment by victor-torres** [comment]
Thanks, @richarddewit 

I also wanted such package so I decided to write one. It has some other bugs and I'm trying to fix them as soon as possible. The one you pasted here seems to be an easy fix. If you find another one, please, open another issue. 

Despite this, I'm using it every day in my work, the basics (per file diff, branch name etc) works fines.

It's nice to know someone else is enjoying it.

**Comment by victor-torres** [comment]
@richarddewit can you try version 0.0.8? If it's broken yet, please reopen the issue.

**Comment by richarddewit** [comment]
:+1: Fixed, thanks!
