### ISSUE TITLE
Uncaught TypeError: Cannot read property 'indexOf' of null

### ISSUE THREAD

**Issue by dampcake** [victor-torres/atom-hg#17]
**Atom Version**: 1.7.2
**System**: Mac OS X 10.11.4
**Thrown From**: [atom-hg](https://github.com/victor-torres/atom-hg) package, v2.0.3
### Stack Trace

Uncaught TypeError: Cannot read property 'indexOf' of null

```
At /Users/adam/.atom/packages/atom-hg/lib/hg-repository.coffee:258

TypeError: Cannot read property 'indexOf' of null
    at HgRepository.module.exports.HgRepository.isPathIgnored (/Users/adam/.atom/packages/atom-hg/lib/hg-repository.coffee:258:49)
    at Directory.module.exports.Directory.updateStatus (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/directory.js:130:16)
    at new Directory (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/directory.js:52:12)
    at Directory.module.exports.Directory.getEntries (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/directory.js:263:30)
    at Directory.module.exports.Directory.reload (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/directory.js:321:20)
    at Directory.module.exports.Directory.expand (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/directory.js:365:12)
    at tree-view-directory.DirectoryView.expand (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/directory-view.js:177:24)
    at tree-view-directory.DirectoryView.toggleExpansion (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/directory-view.js:164:21)
    at TreeView.module.exports.TreeView.entryClicked (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/tree-view.js:470:15)
    at tree-view-directory.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/tree-view.js:188:26)
    at space-pen-div.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at space-pen-div.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```
### Commands

```
     -1:12.8.0 application:new-file (ol.results-view.list-tree.focusable-panel.has-collapsable-children)
     -0:45.7.0 tabs:close-all-tabs (li.texteditor.tab.sortable.right-clicked)
     -0:44.3.0 fuzzy-finder:toggle-file-finder (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui.find-visible)
  4x -0:37.9.0 core:move-down (atom-text-editor.editor.mini.is-focused)
  6x -0:35.6.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:34.3.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:34.3.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:13.9.0 command-palette:toggle (atom-pane.pane.active)
  2x -0:11.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:09.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:09.0 settings-view:check-for-package-updates (atom-pane.pane.active)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by victor-torres** [comment]
This error is probably caused by `@cachedIgnoreStatuses = @getRepo().getRecursiveIgnoreStatuses()` in `refreshStatus`. There's a try/catch in the `getRecursiveIgnoreStatuses` method and null was being returned when an error was found. Now we're returning a blank list, which may remove the indexOf error but you probably still have a problem with the Mercurial command execution (was issue #5 about that?). Could you check the Atom console for errors?

**Comment by victor-torres** [comment]
BTW, version 2.0.4 has been released with that possible fix (fa5ace7)

Can you try it and give us some feedback? :)

**Comment by dampcake** [comment]
I'll see if I can  reproduce it.

**Comment by victor-torres** [comment]
@dampcake any feedback?

**Comment by dampcake** [comment]
Can't reproduce.

**Comment by victor-torres** [comment]
Thank you for the feedback.
