### ISSUE TITLE
Failed to activate the atom-hg package

### ISSUE THREAD

**Issue by goemaeret** [victor-torres/atom-hg#47]
**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [atom-hg](https://github.com/victor-torres/atom-hg) package 2.0.11

### Stack Trace

Failed to activate the atom-hg package

```
At Unexpected end of JSON input

SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at Object.activate (/packages/atom-hg/lib/atom-hg.coffee:6:21)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:218:19)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/app.asar/src/package-manager.js:508:46)
    at /app.asar/src/atom-environment.js:812:28
```

**Comment by TomKemperNL** [comment]
Looks like going from Atom 1.14 to Atom 1.15 breaks the entire plugin... Hoping to get a look in later this week(end?)

**Comment by TomKemperNL** [comment]
Couldn't resist having a short look. This looks like a false alarm. I'm having the exact same problem, but that's because I suspect @goemaeret is running my fork, and not the actual package.

Line 6 in atom-hg.coffee is empty in all released versions, but line 6 in atom-hg.coffee of my fork contains a quick & dirty proxy I was using to track the performance of all calls to the atom-hg plugin (which indeed calls Object.parse on a far-from-stable location).

So I suspect the solution is to switch back to the atom-hg you get from apm install.

**Comment by goemaeret** [comment]
@TomKemperNL Actually after reinstalling the package the problem is solved. It was indeed the forked version that caused this behaviour. So all is good :)

Thx for looking into it!

**Comment by victor-torres** [comment]
Thanks for the feedback, guys!

**Comment by albertcito** [comment]
I have the same issue. I installed and reinstall but it does not works.


**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [atom-hg](https://github.com/victor-torres/atom-hg) package 2.0.14


### Stack Trace

Failed to activate the atom-hg package

```
At e.getOriginURL is not a function

TypeError: e.getOriginURL is not a function
    at atom.project.observeRepositories.subscriptions.add.atom.project.observeRepositories.e (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:212429)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:1172318)
    at Emitter.emit (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:1173759)
    at Project.addPath (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:410818)
    at Project.setPaths (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:409619)
    at e.consume.e (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:412718)
    at Provider.t.exports.Provider.provide (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:1029640)
    at ServiceHub.t.exports.ServiceHub.provide (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:3012661)
    at Package.activateServices (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:3020847)
    at Package.activateNow (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:3017902)
    at measure (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:3017226)
    at Package.measure (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:3014857)
    at activationPromise.activationPromise.Promise (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:3017086)
    at new Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:3017029)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:382643)
    at ~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:899185
    at r (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:893791)
    at o (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:1032547)
    at ChildProcess.n.process.on.e (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:1032753)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

### Commands

```
```

### Non-Core Packages

```
atom-hg 2.0.14 
busy-signal 2.0.0 
chestnut-light-atom-syntax 0.2.1 
file-icons 2.1.27 
intentions 1.1.5 
language-cfml 0.23.0 
linter 2.2.0 
linter-cflint 0.15.0 
linter-ui-default 1.7.1 
minimap 4.29.9 
oceanic-next 1.0.0 
```

**Comment by victor-torres** [comment]
Thank you for contributing with this stack trace report, @albertcito. 

I have created another issue (#55) since it looks like the exception behind this startup error is slightly different.
