### ISSUE TITLE
Error on Startup

### ISSUE THREAD

**Issue by dampcake** [victor-torres/atom-hg#5]
I am getting the following error when Atom starts.

```
Mercurial hg-utils TypeError: Cannot read property 'toString' of null
    at Repository.hgCommand (/Users/adam/.atom/packages/atom-hg/lib/hg-utils.coffee:248:35)
    at Repository.getHgVersion (/Users/adam/.atom/packages/atom-hg/lib/hg-utils.coffee:266:18)
    at Repository.checkBinaryAvailable (/Users/adam/.atom/packages/atom-hg/lib/hg-utils.coffee:64:17)
    at openRepository (/Users/adam/.atom/packages/atom-hg/lib/hg-utils.coffee:431:17)
    at Object.exports.open (/Users/adam/.atom/packages/atom-hg/lib/hg-utils.coffee:438:10)
    at new HgRepository (/Users/adam/.atom/packages/atom-hg/lib/hg-repository.coffee:34:21)
    at Function.module.exports.HgRepository.open (/Users/adam/.atom/packages/atom-hg/lib/hg-repository.coffee:26:11)
    at Object.repositoryForDirectorySync (/Users/adam/.atom/packages/atom-hg/lib/atom-hg.coffee:23:31)
    at Project.module.exports.Project.addPath (/Applications/Atom.app/Contents/Resources/app.asar/src/project.js:249:89)
    at Project.module.exports.Project.setPaths (/Applications/Atom.app/Contents/Resources/app.asar/src/project.js:213:14)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/project.js:356:19
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at ServiceHub.module.exports.ServiceHub.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:30:20)
    at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:350:71)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:184:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:155:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:148:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:145:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:526:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:507:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:502:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:485:46)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:688:21)
    at module.exports (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:86:5)
    at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:41:9)Repository.handleHgError @ hg-utils.coffee:259
/Users/adam/.atom/packages/ember-tabs/lib/ember-pods-project.coffee:17 [ember-tabs] Initiating pods project with root path /Users/adam/Development/labc/projects/labc-web/src/main/javascript
```

**Comment by victor-torres** [comment]
Hello, @dampcake.

Can you try version 0.0.10 and see if this TypeError is fixed?

If it's fixed (and probably is) OK, but you may have a problem with your Mercurial binary path. I presume you're running OS X, is hg on **/usr/local/bin/hg** path? If not, is it in your PATH environment variable?

**Comment by dampcake** [comment]
Yes I am running OS X and hg is in `/usr/local/bin/hg`.

I now get `Mercurial hg-utils Error: Erro trying to execute Mercurial binary with params '--version,--quiet'(…)`.

_Note: Typo in Error_

When running hg --version --quiet from the command line i get the output:
`Mercurial Distributed SCM (version 3.7.2)`

**Comment by dampcake** [comment]
Restart seems to have fixed it.

**Comment by victor-torres** [comment]
> Note: Typo in Error

Sorry, started to write in Brazilian Portuguese 😅

> Restart seems to have fixed it.

May I close the issue?
