### ISSUE TITLE
status-bar throws error at startup after installing atom-hg

### ISSUE THREAD

**Issue by kveretennicov** [victor-torres/atom-hg#53]
Atom 1.8.0
atom-hg 2.0.14
status-bar 1.2.3

```
Cannot read property 'onDidChangeStatus' of undefined
Hide Stack Trace
TypeError: Cannot read property 'onDidChangeStatus' of undefined
    at status-bar-git.GitView.subscribeToRepositories (/usr/share/atom/resources/app.asar/node_modules/status-bar/lib/git-view.js:99:52)
    at status-bar-git.GitView.initialize (/usr/share/atom/resources/app.asar/node_modules/status-bar/lib/git-view.js:34:12)
    at Object.module.exports.activate (/usr/share/atom/resources/app.asar/node_modules/status-bar/lib/main.js:67:16)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:183:20)
    at /usr/share/atom/resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:538:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:497:46)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:754:28
```

**Comment by kveretennicov** [comment]
If I understand correctly, atom-svn suffered from the same breaking change (andischerer/atom-svn#20). They seem to have it fixed with fairly simple changes (andischerer/atom-svn#21). Should work for atom-hg as well?

**Comment by kveretennicov** [comment]
Issue gone after upgrading to Atom 1.19.7, status-bar 1.8.11.
